<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link href="data:image/x-icon;base64,AAABAAEAEBACAAAAAACwAAAAFgAAACgAAAAQAAAAIAAAAAEAAQAAAAAAQAAAAAAAAAAAAAAAAgAAAAAAAAAEBLgAAAAAAP//AAD+fwAA/n8AAP5/AAD+fwAA/n8AAO53AADeewAAwAMAANw7AAD73wAA9+8AAPfvAAD73wAA/D8AAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        rel="icon" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="css/main.css">
    <link rel="stylesheet" href="css/bootstrap.4.0.0.min.css">
    <link rel="stylesheet" href="css/fontawesome-all.css">
    <title>Freebies / XP checker for V:tM characters</title>
</head>

<body>


    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h1>
                        Freebies / XP checker for V:tM characters
                    </h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
			<h1>White Wolf character sheet generator</h1>
		<p>I see the look in your eyes. The look that says, "I have a PDF of the character sheet. Heck, I have the famous fillable sheets from Mr. Gone! What do I need this site for?"</p>
		<p> Heh. This is, as far as I know, the <strong>only</strong> character sheet generator that will actually count your freebie points and XP, and make sure your math is right.</p>
		<p> So have at it. What do you have to lose, but a few minutes?</p>
		<hr>
		<div id="characterArea" class="characterContainer">
			<div id="newCharacter" class="characterBox">
				<div class="spacer"></div>
				<p>New Vampire<br />
				No Clan (yet)<br />
				15 freebies<br />
				15 XP</p>
			</div>
			<div class='holder'>
<div id='load1003' class='loadBox Tremere'>
<p>Plait<br />
Tremere<br />
15 freebies<br />
15 XP</p>
</div><div id='load1004' class='loadBox Malkavian'>
<p>Lila "Banshee" Cassidy<br />
Malkavian<br />
15 freebies<br />
15 XP</p>
</div><div id='load1010' class='loadBox Setite'>
<p>Damian<br />
Setite<br />
15 freebies<br />
15 XP</p>
</div><div id='load1019' class='loadBox Malkavian'>
<p>John Bennerhoff<br />
Malkavian<br />
15 freebies<br />
15 XP</p>
</div><div id='load1024' class='loadBox Assimite'>
<p>Ruby Erics<br />
Assimite<br />
15 freebies<br />
15 XP</p>
</div>			</div>
		</div>
			</div>
        </div>
        <div class="hidden ">
            <script src="js/jquery-3.3.1.min.js "></script>
            <script src="js/bootstrap.4.0.0.min.js "></script>
        </div>
</body>

</html>