<?php 
	/* List of Merits, flaws, and their values from the 20th Aniversary edition */
	$meritsFlawsList = [
		"Physical" => [
			" Merits" => [
				"Acute Sense" => [
					"type" => "Merit",
					"size" => 1
				],
				"Ambidextrous" => [
					"type" => "Merit",
					"size" => 1
				],
				"Bruiser" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Catlike Balance" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Early Riser" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Eat Food" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Friendly Face" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Blush of Health" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Enchanting Voice" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Daredevil" => [
					"type" => "Merit",
					"size"=> 3
				],
				"Efficient Digestion" => [
					"type" => "Merit",
					"size"=> 3
				],
				"Huge Size" => [
					"type" => "Merit",
					"size"=> 4
				],
			],
			" Flaws" => [
				"Hard of Hearing" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Short" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Smell of the Grave" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Tic/Twitch" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Bad Sight (correctable)" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Bad Sight (uncorrectable)" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Fourteenth Generation" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Fifteenth Generation" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Disfigured" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Dulled Bite" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Infectious Bite" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"One Eye" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Vulnerability to Silver" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Open Wound (unsightly)" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Open Wound (disfiguring)" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Addiction" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Child" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Deformity" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Glowing Eyes" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Lame" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Lazy" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Monstours" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Permanent Fangs" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Permanent Wound" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Slow Healing" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Disease Carrier" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Deaf" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Mute" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Thin Blood" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Flesh of the Corpse" => [
					"type" => "Flaw",
					"size"=> 5
				],
				"Infertile Vitae" => [
					"type" => "Flaw",
					"size"=> 5
				],
				"Blind" => [
					"type" => "Flaw",
					"size"=> 6
				],
			]
		],
		"Mental" => [
			" Merits" => [
				"Coldly Logical" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Common Sense" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Concentration" => [
					"type" => "Merit",
					"size"=> 1
				],
				"introspection" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Language" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Time Sense" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Useful Knowledge" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Code of Honor" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Computer Aptitude" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Eidetic Memory" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Light Sleeper" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Natural Linguist" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Calm Heart" => [
					"type" => "Merit",
					"size"=> 3
				],
				"Iron Will" => [
					"type" => "Merit",
					"size"=> 3
				],
				"Precocious" => [
					"type" => "Merit",
					"size"=> 3
				],
			],
			" Flaws" => [
				"Deep Sleeper" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Impatient" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Nightmares" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Prey Exclusion" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Shy" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Soft-Hearted" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Speech Impediment" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Unconvinced" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Amnesia" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Lunacy" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Phobia" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Short Fuse" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Stereotype" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Territorial" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Thirst for Innocence" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Vengeful" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Victim of the Masquerade" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Weak-Willed" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Conspicuous Consumption" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Guild-Wracked" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Flashboacks" => [
					"type" => "Flaw",
					"size"=> 6
				],
			]
		],
		"Social" => [
			" Merits" => [
				"Elysium Regular" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Former Ghoul" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Harmless" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Natural Leader" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Prestigious Sire" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Protégé" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Rep" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Sabbat Survivor" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Boon" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Boon" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Boon" => [
					"type" => "Merit",
					"size"=> 3
				],
				"Boon" => [
					"type" => "Merit",
					"size"=> 4
				],
				"Boon" => [
					"type" => "Merit",
					"size"=> 5
				],
				"Boon" => [
					"type" => "Merit",
					"size"=> 6
				],
				"Bullyboy" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Old Pal" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Lawman's Friend" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Open Road" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Sanctity" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Scholar of Enemies" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Scholar of Others" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Friend of the Underground" => [
					"type" => "Merit",
					"size"=> 3
				],
				"Mole" => [
					"type" => "Merit",
					"size"=> 3
				],
				"Rising Star" => [
					"type" => "Merit",
					"size"=> 3
				],
				"Broken Bond" => [
					"type" => "Merit",
					"size"=> 4
				],
				"clan Friendship" => [
					"type" => "Merit",
					"size"=> 4
				],
				"Primogen/Bishop Friendship" => [
					"type" => "Merit",
					"size"=> 4
				],
			],
			" Flaws" => [
				"Botched Presentation" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"dark Secret" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Expendable" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Incomplete Understanding" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Infamous Sire" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Mistaken Identity" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"New Arrival" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"New Kid" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Recruitment Target" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Sire's Resentment" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Special Responsibility" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Sympathizer" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Enemy" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Enemy" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Enemy" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Enemy" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Enemy" => [
					"type" => "Flaw",
					"size"=> 5
				],
				"Bound" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Catspaw" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Escaped Target" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Failure" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Masquerade Breaker" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Hunted" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Old Flame" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Rival Sires" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Uppity" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Disgrace to the Blood" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Former Prince" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Hunted Like a Dog" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Narc" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Sleeping With the Enemy" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Clan Enmity" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Loathsome Regnant" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Overextended" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Probationary Sect Member" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Blood Hunted (Home City)" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Blood Hunted (Everyone)" => [
					"type" => "Flaw",
					"size"=> 6
				],
				"Laughingstock" => [
					"type" => "Flaw",
					"size"=> 5
				],
				"Red List" => [
					"type" => "Flaw",
					"size"=> 7
				],
			]
		],
		"Supernatural" => [
			" Merits" => [
				"Deceptive Aura" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Healing Touch" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Inoffensive to Aninmals" => [
					"type" => "Merit",
					"size"=> 1
				],
				"Magic Resistance" => [
					"type" => "Merit",
					"size"=> 2
				],
				"Hidden Diablerie" => [
					"type" => "Merit",
					"size"=> 3
				],
				"Lucky" => [
					"type" => "Merit",
					"size"=> 3
				],
				"Oracular Ability" => [
					"type" => "Merit",
					"size"=> 3
				],
				"Spiirit Mentor" => [
					"type" => "Merit",
					"size"=> 3
				],
				"True Love" => [
					"type" => "Merit",
					"size"=> 4
				],
				"Additional Discepline" => [
					"type" => "Merit",
					"size"=> 5
				],
				"Unbondable" => [
					"type" => "Merit",
					"size"=> 5
				],
				"Nine Lives" => [
					"type" => "Merit",
					"size"=> 6
				],
				"True Faith" => [
					"type" => "Merit",
					"size"=> 7
				],
			],
			" Flaws" => [
				"Cast No Reflection" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Cold Breeze" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"repulsed by Garlic" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Touch of Frost" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Cursed" => [
					"type" => "Flaw",
					"size"=> 1
				],
				"Cursed" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Cursed" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Cursed" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Cursed" => [
					"type" => "Flaw",
					"size"=> 5
				],
				"Beacon of the Unholy" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Deathsight" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Eerie Presence" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Lord of the Flies" => [
					"type" => "Flaw",
					"size"=> 2
				],
				"Can't Cross Running Water" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Haunted" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Repelled by Crosses" => [
					"type" => "Flaw",
					"size"=> 3
				],
				"Grip of the Damned" => [
					"type" => "Flaw",
					"size"=> 4
				],
				"Dark Fate" => [
					"type" => "Flaw",
					"size"=> 5
				],
				"Light-Sensitive" => [
					"type" => "Flaw",
					"size"=> 5
				],
			]
		]
	];
?>

	<div class="row px-2">
		<select class="custom-select" id="::ID::" name="::NAME::">
			<option value="null">(Remove this item)</option>
			<option selected disabled>=&gt; Select a Merit or Flaw &lt;=</option>
<?php foreach ($meritsFlawsList as $category => $type) : ?>
	<?php foreach ($type as $t => $item) : ?>
			<option value="<?= $t ?>" style="font-weight: bold;" disabled><?= $category . $t ?></option>
		<?php foreach ($item as $item_ => $data) : ?>
			<option class="<?= $data['type'] ?>" value="<?= $item_ ?>" data-size="<?= $data['size'] ?>">|- <?= $item_ . ' ' . str_repeat('• ',$data['size']) ?></option>
		<?php endforeach; ?>
			<option value="null" disabled style="line-height: .5em"></option>
	<?php endforeach; ?>
<?php endforeach; ?>
	</select>
</div>